server:
  port: 8285
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@//150.136.219.215:1521/SKYNETDB_iad1c7.skynetsndev.skynetvcndev.oraclevcn.com
    username: PRIMADERA
    password: PortalPRI2023*-
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update


Aplication:
  Report:
    soap-service:
      url: https://efdg-test.fa.us6.oraclecloud.com/xmlpserver/services/v2/ReportService?WSDL
      username: INTEGRACION_PRI
      password: Oracle2023*


